
Vagrant.configure("2") do |config|
  #Define name of this virtual machine as "ansible-controller"
  config.vm.define "ansible-controller" do |controller|
    controller.vm.hostname = "controller"
  end
  #The virtual machine will use centos/7 OS
  config.vm.box = "centos/7"
  #Add provision script where we will install ansible on this virtual machine
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum install epel-release -y
    sudo yum install ansible -y
  SHELL
end